[package]
name = "radicle-terminal-tui"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { version = "1.0" }
tuirealm = { version = "1.7.0" }
tui-realm-stdlib = { version = "1.1.6" }
